# Generated by Django 5.2.4 on 2025-08-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionário',
            new_name='Funcionario',
        ),
    ]
